### ISSUE TITLE
Notification - Fenêtre Gestion des Pénalités

### ISSUE THREAD

**Issue by yon-dand** [agilsport/competFFCK#14]
Lorsque l'opérateur modifie une cellule de la colonne "Chrono" de la fenêtre "Gestion", la modification n'est pas visible sur les autres ordinateurs qui affichent la même fenêtre. Il est nécessaire de fermer la fenêtre puis de la rouvrir pour que la modification apparaisse.
Conséquences : nécessité d'attendre la fin de la course du concurrent en cours, pour interrompre la course, et rafraîchir les écrans (au moins de 2 ordis, les autres pouvant se faire en temps masqué)
[Voir démo vidéo](https://competffck.blogspot.com/2020/07/notification-fenetre-gestion-des.html)

**Comment by Pierro68** [comment]
Vu avec AGIL Aujourd'hui. 
La notification des modifications des temps via la fenêtre "gestion" n'est pas opérationnelle volontairement donc c'est normal que les temps modifiés dans la fenêtre gestion n’apparaissent pas instantanément sur la fenêtre gestion d'un autre PC.  
Le principe étant de dire que c'est le chronométreur le maitre des séquences liées au temps et ce, de la fenêtre chrono. C'est la fenêtre chrono et les séquences des laps qui  font foi et en cas de contrôle approfondi des temps.  De plus si pour une raison ou une autre on est amené à "recalculer les temps net a partir des séquences" ces modification manuelles du temps final seront écrasés ... 

C'est vrai qu'on avait parfois pris cette habitude de modifier les temps de la fenêtre gestion ou d'utiliser cette fenêtre sur un autre PC pour un live ou un sepaker mais CompetFFCK a d'autres outils pour ça

Aujourd'hui les notifications des péna se font de la fenêtre "gestion" et c'est normal, j'ai demandé à ce que les notifications style (DSQ) passent également car c'est bien hors chronométrage

**Comment by Pierro68** [comment]
La MAJ 3.1 w permet maintenant la diffusion (affichage) des temps corrigé manuellement de la fenêtre gestion sur un PC,  sur une autre fenêtre gestion ouverte sur un autre PC du réseau.

**Comment by Pierro68** [comment]
La MAJ 3.1 w permet maintenant la diffusion (affichage) des temps corrigé manuellement de la fenêtre gestion sur un PC, sur une autre fenêtre gestion ouverte sur un autre PC du réseau.
