### ISSUE TITLE
Solution sans bidouille pour afficher les horaires des manches 2

### ISSUE THREAD

**Issue by Pierro68** [agilsport/competFFCK#23]
Lors des courses avec des progression simples (phase 2  avec horaires définies et coureurs qui prennent le départ dans le même ordre que la phase 1), l'impression des horaires de la Phase 2 ne se fait pas avant d'avoir terminé la phase 1 sauf bidouille

Impression sans bidouille
![manche 2](https://user-images.githubusercontent.com/95684867/158856127-6de61662-597b-40dd-baa6-8ced8fed33b3.png)

Bidouille = ouvrir la fenêtre chrono de la manche 2 et refermer permet l'affichage des heures de la manche 2
![manche 2 1](https://user-images.githubusercontent.com/95684867/158856224-3a74b868-e604-4f0d-9a4a-fc6886c5480c.png)

**Comment by cyrilc2** [comment]
@Pierro68 
pour moi, la "bidouille" (entrer dans chrono M2) fonctionne aussi en slalom dès lors que la progression est bien * avec Dossard et asc comme critères...
si c'est clt comme critère, impossible de gèrer la M2 tant que M1 pas terminée (mais c'est logique).

noté dans les "évolutions" que si progression "simple", pas de bidouille à faire !!!

**Comment by Pierro68** [comment]
résolu avec la Maj  4.1c
