### ISSUE TITLE
ws_canoe

### ISSUE THREAD

**Issue by strade03** [agilsport/competFFCK#26]
include js adv-1.0.2 ne fonctionne pas sur tous les environnements (windows 7 sous firefox, chrome..)
par contre en transformant le nom du dossier en adv-1-0-2 le problème est résolu.
![ws_canoe](https://user-images.githubusercontent.com/97481110/159575874-50dc2ed6-b21d-471c-9760-5b84df8fb2f2.jpg)

**Comment by strade03** [comment]
Origine du problème est le blocage par les systèmes antipub (Ublock en l’occurrence) ! En le désactivant tout fonctionne normalement.

**Comment by Pierro68** [comment]
On donc je ferme l issue #26 c est ça ?

Le 16 avr. 2022 12:15, StephV ***@***.***> a écrit :

Origine du problème est le blocage par les systèmes antipub (Ublock en l’occurrence) ! En le désactivant tout fonctionne normalement.

**Comment by strade03** [comment]
Plusieurs personnes ont eu le problème, ça vaut peut-être le coup de renommer le dossier pour ne plus avoir le pb avec les bloqueurs de pubs ?
