### ISSUE TITLE
Fenetre Programme : Equipiers Multiples 

### ISSUE THREAD

**Issue by strade03** [agilsport/competFFCK#28]
Le fonctionnement de l'affichage de Équipiers Multiples avec les heures **impose** d'entrer dans le chrono puis en sortir, sinon la liste est vide.

**Comment by Pierro68** [comment]
* depuis fenêtre "dossard" = brut (sans horaires) sur l'ensembles des courses du WE  j'imagine
* depuis fenêtre  "programme"  pour la Q1 par exemple
![pas OK](https://user-images.githubusercontent.com/95684867/161947990-bacca33c-503f-4d84-9e7e-3c5c9403b438.png)

Solution, ouvrir et fermer fenêtre chrono de la phase puis redemander affichage équipier multiples

![OK](https://user-images.githubusercontent.com/95684867/161948172-d428ace1-a8c7-42d4-95df-e3d0b9ebb37e.png)
