### ISSUE TITLE
Rechecker codage liées aux patrouilles en slalom (soucis qui avait été résolu apriori mais qui est réapparu ?)

### ISSUE THREAD

**Issue by Pierro68** [agilsport/competFFCK#39]
Quand on importe une course type course par équipe en slalom, la fenêtre inscription ouvre 3 X 3 concurrents

![equipes](https://user-images.githubusercontent.com/95684867/173375935-31be7512-7789-4579-97a3-de754c92202b.png)

Apriori quand on modifie dans la table (on passe de 3 à 1, cette fenêtre devient OK mais par contre on perd la possibilité de renseigner les pénalités pour les 3 coureurs)

**Comment by agilsport** [comment]
C'est un problème de paramétrage : il y a 2 informations à gérer correctement
1) Le nombre de place dans la table Embarcation 
2) Le nombre d'embarcation dans la table Type_Competition

ici par exemple pour l'épreuve EK1DU15 lié à l'embaraction EK1 on a 3 comme valeur "Place"
Avec comme Type Compétition CHREQ avec une valeur de Nb_embarcation à 3 ..
ce qui fait 3x3 = 9 Equipiers ...

Pour le EK1 la bonne valeur est de 1 ... (à mon avis ...)

Par contre j'ai amélioré le competFFCK dans la fenêtre de gestion des pénalités avec un affichage différent en mono-embarcation ou multi-embarcation (version competFFCK 3.2y ou sup ...)
