### ISSUE TITLE
Erreur Client WebSocket lors changement Phase

### ISSUE THREAD

**Issue by cyrilc2** [agilsport/competFFCK#40]
Le client websocket (live web, phone_passage) reste connecté lorsqu'on sort de la fenêtre chrono... il faut lancer un reset des sockets avant de chronométrer une nouvelle phase.

**Comment by agilsport** [comment]
La connexion "WebSocket" se crée au démarrage du logiciel ou quand on coche les options dans la config Réseau
La connexion "WebSocket" se ferme à la fermeture du logiciel
Mais l'ouverture ou la fermeture du chrono ne joue pas la dessus ...

**Comment by cyrilc2** [comment]
à la réouverture de la fenêtre chrono, sur la page "control.html" , je me retrouvais avec 2 sur la ligne "command" pendant les mondiaux...avec le client websocket coché sur un client de notification... je vais essayer de reproduire à l'occasion ;-)

**Comment by agilsport** [comment]
Le problème existe ... mais c'est plutôt un competFFCK qui ne se ferme pas et du coup le web-socket existe toujours ...
Avec le gestionnaire des taches de Windows on peut savoir facilement savoir le nombre de competFFCK qui tourne et voir si il n'y a pas un competFFCK "zombie" ... on le tue ...et alors plus de web-socket  ...
Il peut y avoir un competFFCK "zombie" quand par exemple la fenêtre de gestion des pénalités se ferme mal ...
(dans la dernière version, j'ai corrigé un soucis dans ce sens ...)
Mais c'est plus cela qu'il faut regarder ... (le pb du web-socket est une conséquence mais pas la cause ...)
