### ISSUE TITLE
Fonction "SetRanking" dans les listes ne gère pas les ex equo

### ISSUE THREAD

**Issue by Pierro68** [agilsport/competFFCK#43]
Dans le paramétrage des liste édition, la fonction "SetRanking" ne sais pas gérer les ex equo

**Comment by agilsport** [comment]
Il faut regarder le 2ième paramètre de la fonction SetRanking  à savoir la clé de tri ...
Si la clé est unique alors pas d'ex equo

Exemple si la clé est :
1) "Tps, Dossard" alors pas d'ex equo (à moins qu'il existe plusieurs bateaux avec le même dossard)
2) "Tps" alors il peut y avoir des ex equo

**Comment by Pierro68** [comment]
Ca fonctionne merci
