### ISSUE TITLE
Décalage Affichage Horloge

### ISSUE THREAD

**Issue by cyrilc2** [agilsport/competFFCK#5]
Vu sur plusieurs machines, décalage entre affichage horloge dans la fenêtre chrono et l'heure réelle (après synchro IMHP).
seulement lag d'affichage... si impulsion keyboard ou IMHP = Heure vraie

**Comment by Pierro68** [comment]
Idem avec un autre chrono (Race time 2). Dans l'absolu cela ne pose pas de soucis tant que les impulsions viennent du chronomodem ou autre chrono extérieur (cellule officielle 
.ou poire de doublage). 
En revanche si on utilise F2 / F7, on a un décalage d'environs 30 centièmes entre F2/F7 et entrée chrono extérieur. Ce décalage reste le même même si les horloges (affichage)  des PC dérivent +- rapidement. Ce qui veut dire quand même que si on fait une séquence manuelle F2/F7. Même si on est précis, le temps ne sera par tout a fait juste

**Comment by cyrilc2** [comment]
En fait l'horloge qui s'affiche n'est pas exactement celle du chrono connecté quel qu'il soit.
C'est un affichage "informatif" sans la précision du chrono.
Ne pas s'y référer pour une synchro de doublage : utiliser la fonction synchro out (Data Sprint / IMHP) ou faire une synchro globale au lancement des Race time.
Les F2/F7 ne sont pas fiables pour du doublage.
