### ISSUE TITLE
fermeture automatique des inscriptions

### ISSUE THREAD

**Issue by cyrilc2** [agilsport/competFFCK#7]
La programmation de la clôture des inscriptions ne semble pas fonctionner... cf SR slalom encore ouverts le 23/11 à 17h avec date de clôture au 22/11/21 23h !!!

**Comment by agilsport** [comment]
C'est surtout que le robot qui fait cette tâche avait été arrêté par erreur ...
Il retourne et donc ça doit résoudre  le soucis

**Comment by cyrilc2** [comment]
oui, c'est revenu dans l'ordre, merci !
