### ISSUE TITLE
Fermer la fenêtre d'attribution des dossard en utilisant la croix bloque le logiciel

### ISSUE THREAD

**Issue by joker-eph** [agilsport/competFFCK#77]
Quand j'ouvre la fenêtre d'attribution des dossard, il y a un bouton "Fermer" en bas à droite qui fonctionne bien, mais si je clique la "croix" pour fermer en haut à droite, la frame "Attribution des Dossards" à l'intérieur de la fenêtre se ferme mais la fenêtre (intitulée "Attribution des Dossards" également) reste ouverte, sans aucun bouton ou control. Je dois alors quitte le logiciel en utilisant le gestionnaire des tâches.

Version 4.1h

**Comment by agilsport** [comment]
corrigé avec la 4.1j ...
