### ISSUE TITLE
Récupération des dates par phase de course dans le live web

### ISSUE THREAD

**Issue by Pierro68** [agilsport/competFFCK#79]
Les dates des phases de la fenêtre paramétrage ne sont pas récupérés pour le live, j'ai l'impression que c'est la date de la phase une qui est prise en compte

![Capture d'écran 2023-03-17 161241](https://user-images.githubusercontent.com/95684867/225949886-ddf9798d-159f-40af-a0f4-10e8a43c2240.png)

![Capture d'écran 2023-03-17 162848](https://user-images.githubusercontent.com/95684867/225949929-12f39878-35ac-44ec-a70c-ed3e6ca93eaf.png)

**Comment by BorisMEISSNER** [comment]
J'ai le même problème dans les éditions, c'est la clée Date_Début qui est dans le footer, et j'ai essayé de mettre la clée Date_Phase à la plce, mais ça ne fonctionne pas ou alors je l'utilise mal.

**Comment by agilsport** [comment]
Pour les éditions le problème est différent ...  les Dates de Phase sont dans la table Competition_Course_Phase et il faut depuis l'édition XML récupérer ces valeurs (Champ Date_phase)
Pour le Live, dans le flux JSON actuel je n'envoie pas l'info actuellement ... je vais corriger ...
