### ISSUE TITLE
Rafraichissement Automatique du Programme épreuve

### ISSUE THREAD

**Issue by cyrilc2** [agilsport/competFFCK#8]
Retour Utilisateurs 
intérêt fort à un rafraichissement automatique de la fenêtre des programmes lorsque gestion ou chrono est ouverte.
idéalement, un rafraichissement à chaque changement d'état d'une épreuve (2 vers 3 ou 3 vers 4).

**Comment by Pierro68** [comment]
une autre issue a été ouverte sur ce sujet
