### ISSUE TITLE
Multi-course: impossible d'imprimer les listes d'inscrits pour le week-end

### ISSUE THREAD

**Issue by joker-eph** [agilsport/competFFCK#80]
Lors de l'organisation d'une double-course (deux manches le samedi et deux manches le dimanche par example), certains compétiteurs sont inscrits sur l'une ou l'autre (ou les deux).
L'attribution des dossards prend bien ceci en compte et affecte les dossards pour l'ensemble des inscrits.
Cependant je ne vois pas comment imprimer les listes d'inscrits pour le week-end, l'edition ne va sortir que les inscrits et les dossards de la première course, même si on sélectionne la seconde.

L'impression des dossards par club est critique pour préparer la distribution et la récupération des dossards.

Workaround: dupliquer la course, changer les inscrits pour forcer tout les inscrits à participer à la première course, et éditer les listes d'inscrits.

Version 4.1h

**Comment by paul45** [comment]
c'est possible a partir de la vue de gestion des dossards

**Comment by Pierro68** [comment]
Effectivement la logique de la distribution des dossards pour un WE multicourse est gérée par cette fenêtre dossards.  Ailleurs on est dans une course ou une phase donc l'affichage est différent et ne reprend que les dossards liées à la dite course
