### ISSUE TITLE
Edition depuis le mode "Chrono" erreur 'impossible d'ouvrir le fichier ".edition/edition.xml"'

### ISSUE THREAD

**Issue by joker-eph** [agilsport/competFFCK#81]
Version 4.1h

![IMG_0930](https://user-images.githubusercontent.com/3372300/226213813-793dd7d4-3806-4218-92f3-7c934fc8dd94.jpeg)

**Comment by Pierro68** [comment]
Je n'ai pas pu reproduire. ni sur mon PC ni sur une install a blanc de competFFCK ???
