### ISSUE TITLE
Colone "état" en gestion de course

### ISSUE THREAD

**Issue by joker-eph** [agilsport/competFFCK#82]
Il y a une colone "état" en mode gestion de course (saisie des pénalité), juste avant les portes, on ne sait pas ce qu'elle indique et les personnes à la saisie des pénalités étaient un peu perturbées de voir un chiffre à cet endroit.

Version 4.1h

**Comment by joker-eph** [comment]
Changer le nom serait pas mal je pense, "état" semble un peu générique :)

**Comment by Pierro68** [comment]
Le libellé a été changé. on a maintenant impr.. ((impressions)
