### ISSUE TITLE
Problème affichage Live WEB

### ISSUE THREAD

**Issue by Pierro68** [agilsport/competFFCK#88]
Les caractères avec accent (club, nom etc..) posent un soucis d'affichage. L'ensemble de l'information club ou identité  est vide quand le nom ou le club a un accent. 

Uniquement sur le live WEB

![Capture d'écran 2023-03-27 102343](https://user-images.githubusercontent.com/95684867/227885611-37d2ed51-0369-4f8e-bd84-90ebfae1ffcb.png)

Sur le live local on est OK

![Capture d'écran 2023-03-27 102353](https://user-images.githubusercontent.com/95684867/227885684-5706c6fe-ed4b-45a8-a60b-604f2669296a.png)

**Comment by agilsport** [comment]
sur le serveur debian la langue par défaut est LANG=fr_FR.UTF-8
Normalement ça doit rester en mémoire même après un roboot ...
La commande dpkg-reconfigure locales permet de rectifier ... bizarre néanmoins ça doit être stable ...
