### ISSUE TITLE
focus après la correction de pénalités

### ISSUE THREAD

**Issue by paul45** [agilsport/competFFCK#94]
Dans la fenêtre gestion (saisi des pénalités) âpres une correction de pénalités le focus passe sur la case suivante de la ligne suivante 
alors qu'il devrais passer a la casse suivante sans changer de ligne

**Comment by Pierro68** [comment]
![Capture d'écran 2023-10-04 114555](https://github.com/agilsport/competFFCK/assets/95684867/9fbe0565-dbad-49a9-9e10-8c4fc510b7b7)

![Capture d'écran 2023-10-04 114638](https://github.com/agilsport/competFFCK/assets/95684867/d0d63904-9051-485b-b551-fe058874bd32)
