### ISSUE TITLE
ABS qui ne se répercute pas dans la fenêtre du passage arrivée

### ISSUE THREAD

**Issue by cyrilc2** [agilsport/competFFCK#97]
Si on transforme une impulsion keyboard, copy ou théorique d'un dossard en ABS, elle est prise en compte au niveau des bateaux à l'arrivée mais pas au niveau des bateaux en course.

le temps tournant demeure et le dossard reste dans la liste des bateaux qui doivent arriver au niveau du point de passage "arrivée"

c'est pris en compte si on relance la fenêtre chrono !

![image](https://github.com/agilsport/competFFCK/assets/33895732/039f3c61-38f9-48b6-8d41-447ba6ce9e3b)

**Comment by Pierro68** [comment]
Soucis réglé dans la version   5.1Q sur le github
